### ISSUE TITLE
Find more efficient way of importing data set

### ISSUE THREAD

**Issue by smeisner10** [CornellDataScience/Reading-Handwriting#1]

**Comment by eswangg** [comment]
Tried using git-lfs; even then, the dataset is too large to be pushed to github (at least without spending money). Plan is to store data locally.
"Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.                           
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."
